version: 0.2
env:
  variables: 
    TERRAFORM_VERSION: "1.5.6"
    #key: "value"
#
#  parameter-store:
#    key: "value"
#
#  secrets-manager:
#    key: "value"

phases:
  install:
    runtime-versions:
      python: 3.12
    
    on-failuer: ABORT

    commands: |
      echo   "Installing terraform"
      echo ##########################################
      yum install -y wget unzip
      yum clean all
      tf_version=$TERRAFORM_VERSION
      wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      chmod 775 terraform
      mv terraform /usr/local/bin/
      terraform --version
      rm terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      ls -al /usr/local/bin/terraform
      echo ##########################################
      echo

  pre_build:
    on-failure: ABORT
    commands: |
      echo 
      echo ##########################################
      echo terraform execution started on `date`
      echo ##########################################
      echo include only plan and initializeation.

  build:
    on-failure: ABORT
    commands: |
      echo ##########################################
      echo terraform execution started on `date`
      cd "$CODEBUILD_SRC_DIR/AWS_Demo/36-Variables-list"
      ls -lathr
      terraform init
      terraform plan -out tfplan
      echo ##########################################
      echo include only build commands no plan

  post_build:
    on-failure: CONTINUE
    commands: |
      echo ##########################################
      echo terraform execution completed on `date`
      echo ##########################################
      echo print lock file content