version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  aws-build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - aws-cli/setup
      
      - run: 
          name: apply terraform code
          command: |
            pwd
            ls
            cd /home/circleci/project/AWS_Demo/01-TransitGateWay
            pwd
            ls
            ./terraform init
            ./terraform apply -auto-approve


workflows:
  apply-terrafrom-workflow:
    jobs:
      - aws-build
