version: 2.1
jobs:
  Installation:
    docker:
      - image: cimg/aws:2024.03

    environment:
      TERRAFORM: "1.5.6"

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Check AWS CLI version"
          command: "aws --version"

      - run:
          name: "Install Terraform"
          command: |
            echo "Installing terraform"
            sudo apt-get install -y wget unzip
            sudo apt clean
            tf_version=$TERRAFORM_VERSION
            wget "https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip"
            unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
            sudo chmod 775 terraform
            sudo mv terraform /usr/local/bin/
            terraform --version
            rm terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
            ls -al /usr/local/bin/terraform
            

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  Provision-infrastructure-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - Installation