version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  terraform: circleci/terraform@3.2.1

jobs:
  aws-build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - aws-cli/setup
      - terraform/apply:
          path: /home/circleci/project/AWS_Demo/01-TransitGateWay
      
      #- run: 
      #    name: apply terraform code
      #    command: |
      #      cd /home/circleci/project/AWS_Demo/01-TransitGateWay
      #      terraform init
      #      terraform apply -auto-approve


workflows:
  apply-terrafrom-workflow:
    jobs:
      - aws-build
